# Project information
site_name: Ravage | Faux Rogue
site_url: https://thefauxrogue.com/
site_author: Faux Rogue
site_description: ""

# Copyright
copyright: Copyright &copy; 2020 - 2021, Faux Rogue

# Theme
theme:
  name: readthedocs
  prev_next_buttons_location: none
  sticky_navigation: false

# Styling
extra_css:
  - "style/release_notes.css"
  - "style/common.css"
  - "style/content.css"
  - "style/copyright.css"
  - "style/index.css"
  - "style/mobile.css"
  - "style/remove.css"
  - "style/sidebar.css"

# Extensions
markdown_extensions:
  - toc:
      permalink: "#"

# Navigation
nav:
  - Getting Started: index.md
  - About:
      - Copyright: about/copyright.md
